<?php

namespace FleurBundle\Repository;

/**
 * BouquetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BouquetRepository extends \Doctrine\ORM\EntityRepository
{
}
